---
apiVersion: v1
kind: Namespace
metadata:
  name: go-admin
---
apiVersion: v1
kind: Service
metadata:
  name: go-admin
  namespace: go-admin
  labels:
    app: go-admin
    service: go-admin
spec:
  ports:
  - port: 8000
    name: http
    protocol: TCP
  selector:
    app: go-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-admin
  namespace: go-admin
data:
  settings.yml: |
    settings:
      application:
        demomsg: "谢谢您的参与，但为了大家更好的体验，所以本次提交就算了吧！\U0001F600\U0001F600\U0001F600"
        enabledp: true
        host: 0.0.0.0
        mode: demo
        name: testApp
        port: 8000
        readtimeout: 10000
        writertimeout: 20000
      database:
        driver: sqlite3
        source: ./go-admin-db.db
      gen:
        dbname: testhhh
        frontpath: ../go-admin-ui/src
      jwt:
        secret: go-admin
        timeout: 3600
      logger:
        # 日志存放路径
        path: temp/logs
        # 日志输出，file：文件，default：命令行，其他：命令行
        stdout: '' #控制台日志，启用后，不输出到文件
        # 日志等级, trace, debug, info, warn, error, fatal
        level: trace
        # 数据库日志开关
        enableddb: true
      queue:
        memory:
          poolSize: 100
      extend:
        amap:
          key: de7a062c984bf828d5d1b3a631a517e4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-admin-v1
  namespace: go-admin
  labels:
    app: go-admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-admin
      version: v1
  template:
    metadata:
      labels:
        app: go-admin
        version: v1
    spec:
      containers:
      - name: go-admin
        image: registry.cn-shanghai.aliyuncs.com/go-admin-team/go-admin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: go-admin
          mountPath: /temp
        - name: go-admin
          mountPath: /static
        - name: go-admin-config
          mountPath: /config/
          readOnly: true
      volumes:
      - name: go-admin
        persistentVolumeClaim:
          claimName: go-admin
      - name: go-admin-config
        configMap:
          name: settings-admin
