kind: pipeline
type: kubernetes
name: drone
steps:
  - name: cmd
    image: alpine
    commands:
    - sed -i 's/DRONE_COMMIT/${DRONE_COMMIT}/g' scripts/k8s/deploy.yml
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      repo: registry.cn-shanghai.aliyuncs.com/go-admin-team/go-admin
      tags: v1.2.2
      registry: registry.cn-shanghai.aliyuncs.com
  - name: dron8s
    image: bh90210/dron8s:latest
    settings:
      yaml:
        - ./scripts/k8s/deploy.yml
      kubeconfig:
        from_secret: kubeconfig
