name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
        with:
          target_repo_url:
            git@gitee.com:go-admin-team/go-admin.git
          ssh_private_key:
            ${{ secrets.GITEE_KEY }}
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 'Mirror to gitlab'
        uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
        with:
          target_repo_url:
            git@gitlab.com:go-admin-team/go-admin.git
          ssh_private_key:
            ${{ secrets.GITLAB_KEY }}
